
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre-build
  build:
    commands:
      - echo ./deployment.sh -b
      - echo ./deployment.sh -p
      - echo ./deployment.sh -d
  post_build:
    commands:
      - echo post-build